config/routes.rb
Rails.application.routes.draw do
  root 'establishments#index'
  ActiveAdmin.routes(self)
  resources :categories, only: :show
  devise_for :users
  resources :establishments, except: :destroy do
    resources :reviews, only: [:create, :destroy]
    resources :images, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.admin?
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :establishments, dependent: :destroy
end

app/models/establishment.rb
class Establishment < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews, dependent: :destroy
  has_many :images, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :category_id, presence: true
  validates :agreement, presence: true
  validates :picture, presence: true

  paginates_per 20

  mount_uploader :picture, ImageUploader

  def quality_food_average
    average = self.reviews.average(:quality_food)
    return average_round(average)
  end

  def service_quality_average
    average = self.reviews.average(:service_quality)
    return average_round(average)
  end

  def interior_average
    average = self.reviews.average(:interior)
    return average_round(average)
  end

  def owerall_average
    average = (quality_food_average + service_quality_average + interior_average) / 3
    return average_round(average)
  end

  private

  def average_round(average)
    if average.nil?
      return 0
    else
      return average.round(1)
    end
  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  belongs_to :establishment

  mount_uploader :image, ImageUploader

  validates :image, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :establishment
end

app/models/user.rb
class User < ApplicationRecord
  has_many :establishments, dependent: :destroy
  has_many :images, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :validatable

  validates :username, presence: true


  def active_for_authentication?
    super && self.is_active? # i.e. super && self.is_active
  end

  def is_active?
    self.active_status?
  end

private

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @establishments = @category.establishments.where(active_status: true).page(params[:page])
  end
end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
  def index
    @categories = Category.all
    if params[:text] != ''
      @establishments = Establishment.where("title LIKE ? or description LIKE ?", "%#{params[:text]}%", "%#{params[:text]}%").where(active_status: true).order('updated_at DESC').page(params[:page])
    else
      @establishments = Establishment.where(active_status: true).order('updated_at DESC').page(params[:page])
    end
  end

  def show
    @establishment = Establishment.find(params[:id])
    redirect_to root_path unless @establishment.active_status?
    @images = @establishment.images
    @reviews = @establishment.reviews.order('updated_at DESC')
    @review_availability = @reviews.find_by(user_id: "#{current_user.id}") if user_signed_in?
  end

  def new
    authenticate_user!
    @establishment = Establishment.new
  end

  def create
    @establishment = Establishment.new(establishment_params)

    if @establishment.save
      redirect_to root_path, notice: 'The establishment will be added after verification'
    else
      render :new
    end

  end

  private

  def establishment_params
    params.require(:establishment).permit(:title, :description, :agreement, :category_id, :picture).merge(user_id: current_user.id)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def create
    @establishment = Establishment.find(params[:establishment_id])
    @image = @establishment.images.build(image_params)
    if @image.save
      redirect_to root_path, notice: 'Yeah!'
    else
      redirect_to root_path, notice: 'NOOOO!'
    end
  end

  private

  def image_params
    params.require(:image).permit(:image).merge(user_id: current_user.id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @establishment = Establishment.find(params[:establishment_id])
    @review = @establishment.reviews.build(review_params)
    @review.user_id = current_user.id
    @review.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def review_params
    params.require(:review).permit(:body, :quality_food, :service_quality, :interior)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/establishments_helper.rb
module EstablishmentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/establishments/_show.html.erb
<link  href="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet"> <!-- 3 KB -->
<script src="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script> <!-- 16 KB --> <!-- only if you need custom infoboxes -->

<div class="row">
  <div class="col-md-5 col-md-offset-2">
    <h1><%= @establishment.title %></h1>
    <p><b>Category: <%= @establishment.category.title %></b></p>
    <p><%= @establishment.description %></p>
  </div>
  <div class="col-md-3">
    <%= image_tag(@establishment.picture_url(:normal)) if @establishment.picture? %>
  </div>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3>Gallery</h3>
      <div class="fotorama col-lg-6" data-nav="thumbs" data-loop="true" data-width="600" data-max-width="100%" data-allowfullscreen="true">
          <% @establishment.images.each do |image| %>
            <%= image_tag(image.image_url(:normal)) %>
          <% end %>
      </div>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3>Ratings</h3>
    <p>Owerall: <%= @establishment.owerall_average %></p>
    <p>Quality of food: <%= @establishment.quality_food_average %></p>
    <p>Service quality: <%= @establishment.service_quality_average %></p>
    <p>Interior: <%= @establishment.interior_average %></p>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3>Reviews</h3>
    <% @establishment.reviews.each do |review| %>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <%= review.user.username %> | <%= review.created_at %>
              <%= link_to 'Delete', establishment_review_path(@establishment, review), class: 'btn btn-danger btn-xs', method: :delete, data: {confirm: "Are you sure?"} %>
        </div>
        <div class="panel-body">
          <p><b><%= review.body %></b></p>
          <p>Quality of food: <%= review.quality_food %></br>
          Servise quality: <%= review.service_quality %></br>
          Interior: <%= review.interior %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>
<div class="row">
  <% @establishments.each do |establishment| %>
    <div class="col-md-5 col-md-offset-1">
      <p><%= link_to image_tag(establishment.picture_url(:normal)),
                     establishment_path(establishment) if establishment.picture? %></p>
      <p><b>Title:</b> <%= link_to establishment.title, establishment_path(establishment) %></p>
      </p>
      <hr>
    </div>
<% end %>
</div>
<%= paginate @establishments %>

app/views/establishments/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Add new place</h1>
      <%= simple_form_for @establishment do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :category_id, collection: Category.all,
                    prompt: "Select Category" %>
        <%= f.input :picture, :as => :file, required: true, hint: ("Maximum 900x600px") %>
        <%= f.input :agreement, as: :boolean, checked_value: true %>

        <%= f.button :submit %>
      <% end %>
  </div>
</div>

app/views/establishments/edit.html.erb
<h1>Establishments#edit</h1>
<p>Find me in app/views/establishments/edit.html.erb</p>

app/views/establishments/index.html.erb
<h1>All establishments</h1>
<div style="margin: 5px; padding: 5px; font-size: 18px">
  <p>
    <% @categories.each do |category| %>
    <%= link_to category.title, category_path(category) %> |
    <% end %>
  </p>
</div>
<div class="row">
  <% @establishments.each do |establishment| %>
    <div class="col-md-5 col-md-offset-1">
      <p>
        <%= link_to image_tag(establishment.picture_url(:normal)),
                     establishment_path(establishment) if establishment.picture? %>
      </p>
      <p><b>Title:</b> <%= link_to establishment.title, establishment_path(establishment) %></p>
      <p><b>Rating:</b><%= establishment.owerall_average %></p>
      <hr>
    </div>
  <% end %>
</div>
<%= paginate @establishments %>

app/views/establishments/new.html.erb
<%= render 'form' %>

app/views/establishments/show.html.erb
<link  href="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet"> <!-- 3 KB -->
<script src="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script> <!-- 16 KB --> <!-- only if you need custom infoboxes -->

<div class="row">
  <div class="col-md-5 col-md-offset-2">
    <h1><%= @establishment.title %></h1>
    <p><b>Category: <%= @establishment.category.title %></b></p>
    <p><%= @establishment.description %></p>
  </div>
  <div class="col-md-3">
    <%= image_tag(@establishment.picture_url(:normal)) if @establishment.picture? %>
  </div>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3>Gallery</h3>
      <div class="fotorama col-lg-6" data-nav="thumbs" data-loop="true" data-width="600" data-max-width="100%" data-allowfullscreen="true">
          <% @images.each do |image| %>
            <%= image_tag(image.image_url(:normal)) %>
          <% end %>
      </div>
      <div class="col-lg-6" style="display: flex; flex-direction: row; justify-content: space-between;">
        <div style='width: 600px;'>
          <div id="map" style='width: 540px; height: 324px;'></div>
        </div>
      </div>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3>Ratings</h3>
    <p>Owerall: <%= @establishment.owerall_average %></p>
    <p>Quality of food: <%= @establishment.quality_food_average %></p>
    <p>Service quality: <%= @establishment.service_quality_average %></p>
    <p>Interior: <%= @establishment.interior_average %></p>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3>Reviews</h3>
    <% @reviews.each do |review| %>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <%= review.user.username %> | <%= review.created_at %>
          <% if user_signed_in? && current_user.id == review.user.id %>
              <%= link_to 'Delete', establishment_review_path(@establishment, review), class: 'btn btn-danger btn-xs', method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
        </div>
        <div class="panel-body">
          <p><b><%= review.body %></b></p>
          <p>Quality of food: <%= review.quality_food %></br>
          Servise quality: <%= review.service_quality %></br>
          Interior: <%= review.interior %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>
<% if user_signed_in? && @review_availability.nil? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Add review</h3>
        <%= simple_form_for [@establishment, @establishment.reviews.new] do |f|%>
          <div class="form-inputs">
            <%= f.input :body, placeholder: 'Add a review...' %>
          </div>
          <div class="form-inputs">
            <%= f.input :quality_food, collection: 1..5 %>
          </div>
          <div class="form-inputs">
            <%= f.input :service_quality, collection: 1..5 %>
          </div>
          <div class="form-inputs">
            <%= f.input :interior, collection: 1..5 %>
          </div>
          <div class="form-actions">
            <%= f.button :submit %>
          </div>
          <br>
        <% end %>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= simple_form_for [@establishment, @establishment.images.new] do |f| %>
      <%= f.input :image, :as => :file, required: true, hint: ("Maximum 900x600px") %>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
      <a class="navbar-brand" href="<%= root_path %>">Rating of establishments</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Add new place", new_establishment_path if user_signed_in? %></li>
      </ul>
        <%= form_tag '/establishments', class: 'navbar-form navbar-left', method: :get do %>
          <div class="form-group"><%= text_field_tag :text, "", class: 'form-control' %></div>
          <%= submit_tag 'Search', class: 'btn btn-default' %>
        <% end  %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.username, edit_user_registration_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><a href="<%= user_session_path %>">Sign in</a></li>
          <li><a href="<%= new_user_registration_path %>">Sign up</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalControlwork</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% unless notice.nil? %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>